language: php
sudo: false

php:
  - "7.0"

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

script: phpunit

before_script:
    - travis_retry composer self-update
    - travis_retry composer update --no-interaction --prefer-source --prefer-stable ${COMPOSER_FLAGS}

install:
  - alias composer=composer\ -n && composer selfupdate
  - composer validate
  - composer --prefer-source install

cache:
  directories:
    - $HOME/.composer/cache
